server:
  port: 80
cors:
  originPatterns: http://localhost:3000,http://localhost:80800
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/beat-depot?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: gustavo
    password: tomate09
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false

cloud:
  aws:
    stack:
      auto: false